name: Run Hot Issue to YouTube

on:
  schedule:
    - cron: '0 11 * * *'  # 매일 오전 11시 (UTC 기준)
    - cron: '0 17 * * *'  # 매일 오후 5시 (UTC 기준)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Chromium Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip uninstall -y moviepy
          pip install moviepy==2.1.2
          pip install -r requirements.txt

      - name: "Debug: Test moviepy.editor import"
        run: python3 -c "import moviepy.editor; print('moviepy.editor imported successfully')"

      - name: Check Python environment
        run: |
          which python3
          python3 --version
          python3 -m pip freeze

      - name: Run hotissue_to_youtube Script
        run: python3 hotissue_to_youtube.py
