name: Run Hot Issue to YouTube

on:
  schedule:
    - cron: '0 11 * * *'  # 매일 오전 11시 (UTC 기준)
    - cron: '0 17 * * *'  # 매일 오후 5시 (UTC 기준)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Chromium Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install system dependencies for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          # moviepy를 GitHub 저장소에서 소스 빌드 방식으로 설치합니다.
          pip install --force-reinstall --no-cache-dir --no-binary :all: git+https://github.com/Zulko/moviepy.git@master
          # requirements.txt에는 moviepy 항목이 없어야 합니다.
          pip install -r requirements.txt

      - name: "Debug: Check moviepy import and version"
        run: |
          python3 -c "import moviepy; print('moviepy version:', moviepy.__version__); print('moviepy file:', moviepy.__file__)"
          python3 -c "import moviepy.editor; print('moviepy.editor imported successfully')"

      - name: "Debug: List contents of moviepy package directory"
        run: |
          MOVIEPY_DIR=$(python3 -c "import moviepy; print(moviepy.__file__.replace('__init__.py',''))")
          echo "Contents of moviepy directory ($MOVIEPY_DIR):"
          ls -la $MOVIEPY_DIR

      - name: Check Python environment
        run: |
          which python3
          python3 --version
          python3 -m pip freeze

      - name: Run hotissue_to_youtube Script
        run: python3 hotissue_to_youtube.py
